### ISSUE TITLE
Readme file is not complete 

### ISSUE THREAD

**Issue by NaveenKCBits** [neerajjsk/Coding-Java-Questions#5]
Readme is the first item usually visitor will see while visiting the repository.
It should include below information -
- What the project does
- Why the project is useful
- How user can get started with the project
- Where user can get help with project
- Who maintains and contributes to the project
[https://github.com/neerajjsk/Coding-Java-Questions](url)

**Comment by neerajjsk** [comment]
Yes ,we need to add that . We are working on it

**Comment by neerajjsk** [comment]
updated the PRs
