### ISSUE TITLE
Questions Missing Code Examples related to OOP Concepts in JAVA

### ISSUE THREAD

**Issue by NaveenKCBits** [neerajjsk/Coding-Java-Questions#6]
Should contains examples of OOP Concepts Implementation like -
- Inheritance
- Encapsulation
- Abstraction 
- Overloading
- Inheritance

[https://github.com/neerajjsk/Coding-Java-Questions](url)

**Comment by neerajjsk** [comment]
This repo is more to coding question rather than OOP concepts , we will cover these concepts using different examples
