### ISSUE TITLE
Coding Style, Best practices  and Coding Standard Document for JAVA not present

### ISSUE THREAD

**Issue by NaveenKCBits** [neerajjsk/Coding-Java-Questions#7]
A documentation can be added for the coders to refer for the best practices and coding guidelines followed industry wide.
- Structuring the Code
- Comments 
- Modularization 
- Coding Standards
- Documenting the project etc.

**Comment by neerajjsk** [comment]
We are working on it , and may be assign this to some new contributor , keeping this issue in open state so that we can track pending works.
