### ISSUE TITLE
Github page is needed for the project

### ISSUE THREAD

**Issue by NaveenKCBits** [neerajjsk/Coding-Java-Questions#8]
GitHub pages are nice way to host website for our project directly from the GitHub repository.
@neerajjsk 
@NaveenKCBits 
@NaveenBaluChakravarthy

[https://github.com/neerajjsk/Coding-Java-Questions](url)

**Comment by neerajjsk** [comment]
Added by @NaveenBaluChakravarthy , closing the issue

**Comment by NaveenKCBits** [comment]
Needs more Changes for GITHUB Pages.

**Comment by neerajjsk** [comment]
re-opening the issue , so that we have track .

**Comment by neerajjsk** [comment]
added PR
